defaults:
  - /snn

model:
  params:
    num_rec_layers: 0
    num_ff_layers: 2
    output_scale: null
    activation_steepness: null
    regularization:
      weights:
        - type: L2
          kwargs:
            strength: ${policy.wl2}

optimizer:
  type: ${optimizer.type}
  params:
    lr: 0.004

learning:
  params:
    unroll_steps: 20
    deterministic_transition: True