defaults:
  - /snn_alif

model:
  params:
    num_rec_layers: 0
    num_ff_layers: 2
    output:
      kwargs:
        weight_scale: 0.5
        output_scale: 1.0
        learn_weight_scale: false
        learn_output_scale: false
        apply_tanh: true
    regularization:
      weights:
        - type: L2
          kwargs:
            strength: ${policy.wl2}

optimizer:
  type: ${optimizer.type}
  params:
    lr: 0.004

learning:
  params:
    relative_l2_weight: 1.0
    unroll_steps: 20
    deterministic_transition: True