defaults:
  - /snn

model:
  params:
    num_rec_layers: 0
    num_ff_layers: 2
    output_scale: 1.0
    regularization:
      weights:
        - type: L2
          kwargs:
            strength: 0.001

optimizer:
  type: ${optimizer.type}
  params:
    lr: 0.0005

learning:
  params:
    unroll_steps: 20
    deterministic_transition: True