defaults:
  - /snn_alif

model:
  params:
    # num_rec_layers: 1
    # num_layers: 1
    output:
      kwargs:
        weight_scale: 0.5
        output_scale: 1.0
        learn_weight_scale: true
        learn_output_scale: false
        apply_tanh: true
    regularization:
      weights:
        - type: L2
          kwargs:
            strength: ${policy.wl2}

optimizer:
  type: ${optimizer.type}
  params:
    lr: 0.002

learning:
  params:
    unroll_steps: 20
    deterministic_transition: True