defaults:
  - /snn_alif

model:
  params:
    num_rec_layers: 1
    # num_layers: 1
    readout:
      kwargs:
        weight_scale: 0.005
        output_scale: 1.0
        learn_weight_scale: true
        learn_output_scale: false
        apply_tanh: false
    regularization:
      weights:
        - type: L2
          kwargs:
            strength: ${transition.wl2}

optimizer:
  type: ${optimizer.type}
  params:
    lr: ${optimizer.params.lr}

learning:
  params:
    unroll_steps: 5
