defaults:
  - /snn

model:
  params:
    num_rec_layers: 1
    num_ff_layers: 1 
    output_scale: null
    activation_steepness: 0.1
    regularization:
      weights:
        - type: L2
          kwargs:
            strength: ${transition.wl2}

optimizer:
  type: ${optimizer.type}
  params:
    lr: 0.001

learning:
  params:
    autoregressive: 0.0
    unroll_steps: 5
