defaults:
  - task: reacher
  - agent: pred_agent
  - policy: snn_policy
  - transition: snn_transition
  - wandb: wandb
  - _self_

seed: 42
experiment: default
device: cuda

task:
  num_envs: 25
  params:
    render_mode: human

