defaults:
  - task: reacher
  - agent: pred_agent
  - policy: snn_policy
  - transition: snn_transition
  - logging: logging
  - _self_

seed: 42
experiment: test
device: cuda

model:
  time:
    dt: 0.002
    tau_mem: 0.02
    tau_syn: 0.01
  activation:
    type: sigmoidspike
    beta: 25
  connection:
    n_dims: null
  hidden_dim: 
    - 1024
    - 512
  initializer:
    sigma_u: 1.0
    nu: 100
    bias_scale: 1.0
    scaling: 1.0
  input:
    scaling: 1.0
#  output:
#    activation_steepness: null

optimizer:
  type: adam
  params:
    lr: 0.0005

LowerBoundL2:
  strength: 0.0
  threshold: -10.0
  basis: mem
UpperBoundL2:
  strength: 0.0
  threshold: 0.3
  basis: out

task:
  params:
    render_mode: rgb_array
    full_target_obs: false

run:
  load_dir: null
  prediction_unroll: 20
  eval_first: true
  early_stop_metric: "test average reward"
  early_stop_patience: 20
  early_stop_mode: "max"
  lr_decay: 0.97

plotting:
  render_every: 20
  prediction_animation_unroll: 50  # change back to 50 or so
  prediction_animation_step: 5

learning:
  total_steps: 400_000

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}