defaults:
  - task: reacher
  - agent: pred_agent
  - policy: prnn_policy
  - transition: prnn_transition
  - wandb: wandb
  - _self_

seed: 42
experiment: default
device: cuda

task:
  num_envs: 25
  params:
    render_mode: human

run:
  load_path: null