defaults:
  - task: reacher
  - agent: pred_agent
  - policy: prnn_policy
  - transition: prnn_transition
  - logging: logging
  - _self_

seed: 42
experiment: default
device: cuda

task:
  num_envs: 25
  num_eval_envs: 8
  params:
    render_mode: rgb_array

run:
  load_dir: null
  render_every: 2