defaults:
  - task: reacher
  - agent: pred_agent
  - policy: snn_policy
  - transition: snn_transition
  - logging: logging
  - _self_

seed: 777
experiment: default
device: cuda

model:
  time:
    dt: 0.002
    tau_mem: 0.02
    tau_syn: 0.01

task:
  num_envs: 25
  num_eval_envs: 8
  params:
    render_mode: rgb_array

run:
  load_dir: null
  render_every: 20

learning:
  total_steps: 1_000_000