defaults:
  - task: reacher
  - agent: pred_agent
  - policy: snn_policy
  - transition: snn_transition
  - logging: logging
  - _self_

seed: 42
experiment: default
device: cuda

model:
  time:
    dt: 0.002
    tau_mem: 0.02
    tau_syn: 0.01

optimizer:
  type: smorms3
  params:
    lr: 0.0005

regularization:
  weight:
    l2: 0.001

task:
  num_envs: 25
  num_eval_envs: 8
  params:
    render_mode: rgb_array
    full_target_obs: false

run:
  load_dir: null
  prediction_unroll: 20

plotting:
  render_every: 20
  prediction_animation_unroll: 50
  prediction_animation_step: 2

learning:
  total_steps: 500_000