defaults:
  - task: reacher
  - agent: pred_agent
  - policy: snn_policy
  - transition: snn_transition
  - logging: logging
  - _self_

seed: 42
experiment: default
device: cuda

model:
  time:
    dt: 0.002
    tau_mem: 0.02
    tau_syn: 0.01
  activation:
    type: sigmoidspike
    beta: 25
  connection:
    n_dims: null
  hidden_dim: 
    - 1024
    - 512
  initializer:
    sigma_u: 1.0
    nu: 10
    bias_scale: 1.0
    scaling: 1.0
  input:
    scaling: 0.01
  output:
    activation_steepness: 1.0

optimizer:
  type: smorms3
  params:
    lr: 0.0005

LowerBoundL2:
  strength: 0.0
  threshold: 0.0
  basis: out
UpperBoundL2:
  strength: 0.0
  threshold: 0.3
  basis: out

task:
  num_envs: 25
  num_eval_envs: 8
  params:
    render_mode: rgb_array
    full_target_obs: false

run:
  load_dir: null
  prediction_unroll: 20
  eval_first: true

plotting:
  render_every: 20
  prediction_animation_unroll: 50
  prediction_animation_step: 2

learning:
  total_steps: 10_000

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}