model:
  type: prnn
  params:
    hidden_dim: 512
    activation_fn: 
      type: lrelu

optimizer:
  type: smorms3
  params:
    lr: 0.0005

learning:
  params:
    batch_size: 256
    batches_per_iteration: 10
    max_norm: 30
    warmup_steps: 5