model:
  type: prnn
  params:
    hidden_dim: 512
    activation: 
      type: lrelu

optimizer:
  type: smorms3
  params:
    lr: 0.0005

learning:
  batches_per_iteration: 10
  params:
    batch_size: 256
    max_norm: 30
    warmup_steps: 5