model:
  type: rsnn
  params:
    hidden_dim: 1024
    dt: ${model.time.dt}
    repeat_input: 8
    out_style: last
    input:
      type: input
      kwargs: {}
    neuron:
      type: lif
      kwargs:
        tau_mem: ${model.time.tau_mem}
        tau_syn: ${model.time.tau_syn}
    readout:
      type: readout
      kwargs:
        tau_mem: ${model.time.tau_mem}
        tau_syn: ${model.time.tau_syn}
        n_readouts: 20
    connection:
      type: bottleneck
      kwargs:
        bias: true
        n_dims: 20
    initializer:
      type: normal
      kwargs:
        time_step: ${model.time.dt}
        sigma_u: 1.0
        nu: 100
        bias_scale: 1.0
        scaling: 1.0
    activation:
      type: sigmoidspike
      activation_kwargs:
        beta: 25
    regularization:
      activity:
        - type: LowerBoundL2
          kwargs:
            strength: 0.01
            threshold: 0.1
            basis: mem
            dims: null
        - type: UpperBoundL2
          kwargs:
            strength: 1.0
            threshold: 0.3
            basis: mem
            dims: 1
      weights:
      - type: L2
        kwargs:
          strength: 0.005

optimizer:
  type: smorms3
  params:
    lr: 0.0005

learning:
  batches_per_iteration: 10
  params:
    batch_size: 256
    max_norm: 30
    warmup_steps: 5