model:
  type: rsnn
  params:
    hidden_dim: 1024
    connection_dims: 20
    dt: 0.002
    repeat_input: 8
    nu: 100
    out_style: last
    lowerBoundL2Strength: 0.0
    upperBoundL2Strength: 1.0
    weightL2Strength: 0.0
    activation_fn:
      type: sigmoidspike
      activation_kwargs:
        beta: 20.0
        gamma: 1.0
    flif_kwargs:
      tau_mem: 0.02
      tau_syn: 0.01
      reset: sub
    readout_kwargs:
      n_pop: 25

optimizer:
  type: smorms3
  params:
    lr: 0.0005

learning:
  params:
    batch_size: 256
    batches_per_iteration: 10
    max_norm: 30
    warmup_steps: 5