model:
  type: rsnn
  params:
    # num_rec_layers: ${model.num_rec_layers}
    num_layers: ${model.num_layers}
    hidden_dim: ${model.hidden_dim}
    dt: ${model.time.dt}
    repeat_input: ${model.repeat_input}
    out_style: last
    encoder: ${model.encoder}
    input:
      type: input
      kwargs: 
        input_scale: ${model.input.input_scale}
        learn_input_scale: ${model.input.learn_input_scale}
    neuron:
      type: alif
      kwargs:
        reset: sub
        tau_mem: ${model.time.tau_mem}
        tau_syn: ${model.time.tau_syn}
        tau_ada: ${model.time.tau_ada}
        learn_mem: ${model.time.learn_tau_mem}
        learn_syn: ${model.time.learn_tau_syn}
        learn_ada: ${model.time.learn_tau_ada}
        mem_param: ${model.time.mem_param}
        syn_param: ${model.time.syn_param}
        ada_param: ${model.time.ada_param}
    readout:
      type: readout
      kwargs:
        tau_mem: ${model.time.tau_mem}  # currently needs to be the same as the neuron tau_mem
        tau_syn: ${model.time.tau_syn}  # currently needs to be the same as the neuron tau_syn
        learn_mem: ${model.time.learn_tau_mem}
        learn_syn: ${model.time.learn_tau_syn}
        mem_param: ${model.time.mem_param}
        syn_param: ${model.time.syn_param}
    connection:
      kwargs:
        bias: true
        n_dims: ${model.connection.n_dims}
        latent_bias: ${model.connection.latent_bias}
    tau_initializer:
      stds:
        tau_mem: ${model.time.tau_mem_std}
        tau_syn: ${model.time.tau_syn_std}
        tau_ada: ${model.time.tau_ada_std}
    initializer:
      type: normal
      kwargs:
        alpha: ${model.initializer.alpha}
        mu_u: ${model.initializer.mu_u}
        time_step: ${model.time.dt}
        sigma_u: ${model.initializer.sigma_u}
        nu: ${model.initializer.nu}
        bias_scale: ${model.initializer.bias_scale}
        scaling: ${model.initializer.scaling}
    activation:
      type: ${model.activation.type}
      kwargs:
        beta: ${model.activation.beta}
    regularization:
      activity:
        - type: LowerBoundL2
          kwargs:
            strength: ${LowerBoundL2.strength}
            threshold: ${LowerBoundL2.threshold}
            basis: ${LowerBoundL2.basis}
            dims: ${LowerBoundL2.dims}
        - type: UpperBoundL2
          kwargs:
            strength: ${UpperBoundL2.strength}
            threshold: ${UpperBoundL2.threshold}
            basis: ${UpperBoundL2.basis}
            dims: ${UpperBoundL2.dims}
      weights:
      - type: L2
        kwargs:
          strength: 0.0

optimizer: ${optimizer}

learning:
  batches_per_iteration: ${learning.batches_per_iteration}
  params:
    relative_l2_weight: 1.0
    batch_size: 256
    max_norm: 30
    warmup_steps: 5